name: gymya_users
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  table_calendar: ^3.0.9  # ✅ Dependencia agregada correctamente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2  # Agregar el paquete flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - lib/Recursos/Img/Bienvenida.jpg
    - lib/Recursos/Img/Logo.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Black.ttf
        - asset: lib/fonts/Montserrat-BlackItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Bold.ttf
        - asset: lib/fonts/Montserrat-BoldItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-ExtraBold.ttf
        - asset: lib/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-ExtraLight.ttf
        - asset: lib/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Light.ttf
        - asset: lib/fonts/Montserrat-LightItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Medium.ttf
        - asset: lib/fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Regular.ttf
        - asset: lib/fonts/Montserrat-SemiBold.ttf
        - asset: lib/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: lib/fonts/Montserrat-Thin.ttf
        - asset: lib/fonts/Montserrat-ThinItalic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Recursos/Img/Logo.jpg"  # Ruta de tu logo para el ícono de la app
